//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace database.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cart
    {
        public int product_id { get; set; }
        public Nullable<System.DateTime> added_at { get; set; }

         public virtual Product Product { get; set; }
        public virtual ICollection<Product> Products { get; set; }
    }
}
